apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worldsbx2b-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: worldsbx2b.cloudapp.azure.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: worldsbx2b-service
                port:
                  number: 80
