name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        id: apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Extract ACR Credentials
        id: acr-creds
        run: |
          echo "::set-output name=login_server::$(terraform output -raw registry_login_server)"
          echo "::set-output name=username::$(terraform output -raw registry_username)"
          echo "::set-output name=password::$(terraform output -raw registry_password)"

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ steps.acr-creds.outputs.login_server }}
          username: ${{ steps.acr-creds.outputs.username }}
          password: ${{ steps.acr-creds.outputs.password }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ steps.acr-creds.outputs.login_server }}/my-web-app:latest .
          docker push ${{ steps.acr-creds.outputs.login_server }}/my-web-app:latest
