name: build and release

on:
  push:
    branches:
      - '**'

jobs:
- template: templates/tf-init.yaml
- template: templates/az-login.yaml

    steps:
      - template: templates/az-cmds.yaml

      - name: Extract ACR Credentials
        id: acr-creds
        run: |
          echo "::set-output name=login_server::$(terraform output -raw registry_login_server)"
          echo "::set-output name=username::$(terraform output -raw registry_username)"
          echo "::set-output name=password::$(terraform output -raw registry_password)"

  docker_build:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ steps.terraform.outputs.acr-creds.outputs.username }}
          password: ${{ steps.terraform.outputs.acr-creds.outputs.password }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/worldsbx2b:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/worldsbx2b:latest

  kubernetes:
    runs-on: ubuntu-latest
    needs: docker_build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.19.7

      - name: Get AKS credentials
        run: az aks get-credentials --resource-group ${terraform.workspace} --name ${terraform.workspace}_aks_cluster

      - name: Substitute ACR Image in Kubernetes Manifest
        run: |
          sed -i 's|<ACR_LOGIN_SERVER>|${{ secrets.ACR_LOGIN_SERVER }}|g' k8s-deployment.yml

      - name: Apply Kubernetes manifests
        run: kubectl apply -f deployment.yml
